### ISSUE TITLE
How to use the script on client side

### ISSUE THREAD

**Issue by worldzaki** [derhuerst/flickr-photo-url#8]
How to embed the script in HTML file with <script></script> tag and execute it from the browser?

**Comment by derhuerst** [comment]
Most npm packages can be used in the browser, including this one.

You have to bundle them using [`browserify`](http://browserify.org) or [`webpack`](https://webpack.js.org):

```shell
npm install flickr-photo-url
```

```js
// index.js
const url = require('flickr-photo-url')

url('gilad_rom', 24148019753, url.sizes.original)
.then(console.log, console.error)
```

```shell
npm i webpack webpack-cli -D
webpack --mode production index.js
# use dist/main.js for the <script> tag
```

**Comment by derhuerst** [comment]
Please reopen if you have more questions about this.
